- name: my first ansible playbook 
  hosts: webservers
  vars:
     printMsg:  Completed all tasks
  vars_prompt:
          name: copypath
          prompt: Enter copy path
          private: no
  become: yes
  tasks:
        - name: Apt get update
          apt:
                upgrade: yes
                update_cache: yes  
        - name: Installation task
          apt:
               name: apache2
               state: present
        - name: Copy task
          copy:
               src: prem.txt
               dest: "{{copypath}}"
          notify: restart apache2     
  handlers:             
        - name: restart apache2
          service:
                  name: apache2
                  state: restarted
          register: out
        - name: Debug test
          debug:
              msg: "{{out.state}}"
