- name: first play
  hosts: webservers
  become: yes
  gather_facts: no
  tasks:
       - name: apt task
         apt:
                 name: apache2
                 state: present
       - name: copy task
         copy:
                 src: 5.yaml
                 dest: /opt
         ignore_errors: yes
       - name: service task
         service:
                 name: apache2
                 state: restarted
